language: generic

services:
  - docker

script:
  - docker build -t quay.io/adrianlucrececeleste/travis-quay-tutorial:$TRAVIS_BRANCH -t quay.io/montana/multi-arch-travis:latest .

deploy:
  - provider: script
    script: bash build
