language: generic
os: linux 

arch:
- ppc64le
- s390x

services:
  - docker-ce



script:
  - docker pull quay.io/montana/ubuntu
  - export DOCKER_CLI_EXPERIMENTAL=enabled

deploy:
  provider: script
  script: 
  - bash build.sh
  
  on:
    branch: master

#
