language: generic

services:
  - docker

script:
  - docker pull quay.io/montana/ubuntu

deploy:
  provider: script
  script: 
  - bash build.sh
  - bash create-multi-arch.sh
  on:
    branch: master
